//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDMaker {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    public sealed partial class ScreenshotSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ScreenshotSettings defaultInstance = ((ScreenshotSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ScreenshotSettings())));
        
        public static ScreenshotSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string a_AspectRatio {
            get {
                return ((string)(this["a_AspectRatio"]));
            }
            set {
                this["a_AspectRatio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0")]
        public decimal b_SkipBlank {
            get {
                return ((decimal)(this["b_SkipBlank"]));
            }
            set {
                this["b_SkipBlank"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0")]
        public decimal B_OmitBegin {
            get {
                return ((decimal)(this["B_OmitBegin"]));
            }
            set {
                this["B_OmitBegin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal c_Columns {
            get {
                return ((decimal)(this["c_Columns"]));
            }
            set {
                this["c_Columns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal C_CutMovie {
            get {
                return ((decimal)(this["C_CutMovie"]));
            }
            set {
                this["C_CutMovie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal D_EdgeDetection {
            get {
                return ((decimal)(this["D_EdgeDetection"]));
            }
            set {
                this["D_EdgeDetection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0")]
        public decimal E_OmitEnd {
            get {
                return ((decimal)(this["E_OmitEnd"]));
            }
            set {
                this["E_OmitEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tahomabd.ttf")]
        public string f_Font {
            get {
                return ((string)(this["f_Font"]));
            }
            set {
                this["f_Font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("000000")]
        public string F_FontColor {
            get {
                return ((string)(this["F_FontColor"]));
            }
            set {
                this["F_FontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public decimal g_GapBetweenShots {
            get {
                return ((decimal)(this["g_GapBetweenShots"]));
            }
            set {
                this["g_GapBetweenShots"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public decimal h_MinHeight {
            get {
                return ((decimal)(this["h_MinHeight"]));
            }
            set {
                this["h_MinHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool i_InfoOff {
            get {
                return ((bool)(this["i_InfoOff"]));
            }
            set {
                this["i_InfoOff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool I_IndivScreens {
            get {
                return ((bool)(this["I_IndivScreens"]));
            }
            set {
                this["I_IndivScreens"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("97")]
        public decimal j_JpgQuality {
            get {
                return ((decimal)(this["j_JpgQuality"]));
            }
            set {
                this["j_JpgQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EEEEEE")]
        public string k_ColorBackground {
            get {
                return ((string)(this["k_ColorBackground"]));
            }
            set {
                this["k_ColorBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool n_Priority {
            get {
                return ((bool)(this["n_Priority"]));
            }
            set {
                this["n_Priority"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_s.txt")]
        public string N_InfoSuffix {
            get {
                return ((string)(this["N_InfoSuffix"]));
            }
            set {
                this["N_InfoSuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_s.jpg")]
        public string o_OutputSuffix {
            get {
                return ((string)(this["o_OutputSuffix"]));
            }
            set {
                this["o_OutputSuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string O_OutputDir {
            get {
                return ((string)(this["O_OutputDir"]));
            }
            set {
                this["O_OutputDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool p_PauseBeforeExit {
            get {
                return ((bool)(this["p_PauseBeforeExit"]));
            }
            set {
                this["p_PauseBeforeExit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool P_QuitAfterDone {
            get {
                return ((bool)(this["P_QuitAfterDone"]));
            }
            set {
                this["P_QuitAfterDone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public decimal r_Rows {
            get {
                return ((decimal)(this["r_Rows"]));
            }
            set {
                this["r_Rows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public decimal s_TimeStep {
            get {
                return ((decimal)(this["s_TimeStep"]));
            }
            set {
                this["s_TimeStep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool t_TimeStamp {
            get {
                return ((bool)(this["t_TimeStamp"]));
            }
            set {
                this["t_TimeStamp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool T_Text {
            get {
                return ((bool)(this["T_Text"]));
            }
            set {
                this["T_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool v_Verbose {
            get {
                return ((bool)(this["v_Verbose"]));
            }
            set {
                this["v_Verbose"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal w_Width {
            get {
                return ((decimal)(this["w_Width"]));
            }
            set {
                this["w_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool W_Update {
            get {
                return ((bool)(this["W_Update"]));
            }
            set {
                this["W_Update"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool z_Seek {
            get {
                return ((bool)(this["z_Seek"]));
            }
            set {
                this["z_Seek"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string Z_NonSeek {
            get {
                return ((string)(this["Z_NonSeek"]));
            }
            set {
                this["Z_NonSeek"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4:2")]
        public string L_InfoLocation {
            get {
                return ((string)(this["L_InfoLocation"]));
            }
            set {
                this["L_InfoLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int InfoTextIndex {
            get {
                return ((int)(this["InfoTextIndex"]));
            }
            set {
                this["InfoTextIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int InfoTimestampIndex {
            get {
                return ((int)(this["InfoTimestampIndex"]));
            }
            set {
                this["InfoTimestampIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public decimal F_FontSize {
            get {
                return ((decimal)(this["F_FontSize"]));
            }
            set {
                this["F_FontSize"] = value;
            }
        }
    }
}
